#
# Makefile shared stuff for other makefiles
#

OSMACHINE := $(shell uname -m)
ifneq ($(OSMACHINE), i686)
	OSBITS := 64
else
	OSBITS := 32
endif
ifeq ($(MAKECMDGOALS),)
	MAKECMDGOALS = all
endif
ifneq ($(filter %32,$(MAKECMDGOALS)),)
	OSBITS := 32
else
ifneq ($(filter %64,$(MAKECMDGOALS)),)
	OSBITS := 64
endif
endif

IsMakeVersion = $(filter $(1),$(firstword $(sort $(MAKE_VERSION) \ $(1))))

# END OF FILE
