/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class loaders_pilatus_PilatusLoader */

#ifndef _Included_loaders_pilatus_PilatusLoader
#define _Included_loaders_pilatus_PilatusLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loaders_pilatus_PilatusLoader
 * Method:    loadPilatus
 * Signature: (Ljava/lang/String;)Lloaders/pilatus/PilatusData;
 */
JNIEXPORT jobject JNICALL Java_loaders_pilatus_PilatusLoader_loadPilatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     loaders_pilatus_PilatusLoader
 * Method:    loadHeader
 * Signature: (Ljava/lang/String;)Lloaders/pilatus/PilatusHeader;
 */
JNIEXPORT jobject JNICALL Java_loaders_pilatus_PilatusLoader_loadHeader
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
