output64/JNIException.o : JNIException.cpp JNIException.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/String.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/CallTrace.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/String.h
