/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iucr.cbflib;

public class uintP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public uintP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(uintP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbfJNI.delete_uintP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public uintP() {
    this(cbfJNI.new_uintP(), true);
  }

  public void assign(long value) {
    cbfJNI.uintP_assign(swigCPtr, this, value);
  }

  public long value() {
    return cbfJNI.uintP_value(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_int cast() {
    long cPtr = cbfJNI.uintP_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static uintP frompointer(SWIGTYPE_p_unsigned_int t) {
    long cPtr = cbfJNI.uintP_frompointer(SWIGTYPE_p_unsigned_int.getCPtr(t));
    return (cPtr == 0) ? null : new uintP(cPtr, false);
  }

}
