/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iucr.cbflib;

public interface cbfConstants {
  public final static String CBF_API_VERSION = cbfJNI.CBF_API_VERSION_get();
  public final static String CBF_DIC_VERSION = cbfJNI.CBF_DIC_VERSION_get();
  public final static int CBF_LINELENGTH_10 = cbfJNI.CBF_LINELENGTH_10_get();
  public final static int CBF_LINELENGTH_11 = cbfJNI.CBF_LINELENGTH_11_get();
  public final static int CBF_INIT_READ_BUFFER = cbfJNI.CBF_INIT_READ_BUFFER_get();
  public final static int CBF_INIT_WRITE_BUFFER = cbfJNI.CBF_INIT_WRITE_BUFFER_get();
  public final static int CBF_TRANSFER_BUFFER = cbfJNI.CBF_TRANSFER_BUFFER_get();
  public final static int CBF_FORMAT = cbfJNI.CBF_FORMAT_get();
  public final static int CBF_ALLOC = cbfJNI.CBF_ALLOC_get();
  public final static int CBF_ARGUMENT = cbfJNI.CBF_ARGUMENT_get();
  public final static int CBF_ASCII = cbfJNI.CBF_ASCII_get();
  public final static int CBF_BINARY = cbfJNI.CBF_BINARY_get();
  public final static int CBF_BITCOUNT = cbfJNI.CBF_BITCOUNT_get();
  public final static int CBF_ENDOFDATA = cbfJNI.CBF_ENDOFDATA_get();
  public final static int CBF_FILECLOSE = cbfJNI.CBF_FILECLOSE_get();
  public final static int CBF_FILEOPEN = cbfJNI.CBF_FILEOPEN_get();
  public final static int CBF_FILEREAD = cbfJNI.CBF_FILEREAD_get();
  public final static int CBF_FILESEEK = cbfJNI.CBF_FILESEEK_get();
  public final static int CBF_FILETELL = cbfJNI.CBF_FILETELL_get();
  public final static int CBF_FILEWRITE = cbfJNI.CBF_FILEWRITE_get();
  public final static int CBF_IDENTICAL = cbfJNI.CBF_IDENTICAL_get();
  public final static int CBF_NOTFOUND = cbfJNI.CBF_NOTFOUND_get();
  public final static int CBF_OVERFLOW = cbfJNI.CBF_OVERFLOW_get();
  public final static int CBF_UNDEFINED = cbfJNI.CBF_UNDEFINED_get();
  public final static int CBF_NOTIMPLEMENTED = cbfJNI.CBF_NOTIMPLEMENTED_get();
  public final static int CBF_NOCOMPRESSION = cbfJNI.CBF_NOCOMPRESSION_get();
  public final static char CBF_TOKEN_NULL = cbfJNI.CBF_TOKEN_NULL_get();
  public final static char CBF_TOKEN_WORD = cbfJNI.CBF_TOKEN_WORD_get();
  public final static char CBF_TOKEN_SQSTRING = cbfJNI.CBF_TOKEN_SQSTRING_get();
  public final static char CBF_TOKEN_DQSTRING = cbfJNI.CBF_TOKEN_DQSTRING_get();
  public final static char CBF_TOKEN_SCSTRING = cbfJNI.CBF_TOKEN_SCSTRING_get();
  public final static char CBF_TOKEN_BIN = cbfJNI.CBF_TOKEN_BIN_get();
  public final static char CBF_TOKEN_MIME_BIN = cbfJNI.CBF_TOKEN_MIME_BIN_get();
  public final static char CBF_TOKEN_TMP_BIN = cbfJNI.CBF_TOKEN_TMP_BIN_get();
  public final static char CBF_TOKEN_BKTSTRING = cbfJNI.CBF_TOKEN_BKTSTRING_get();
  public final static char CBF_TOKEN_BRCSTRING = cbfJNI.CBF_TOKEN_BRCSTRING_get();
  public final static char CBF_TOKEN_PRNSTRING = cbfJNI.CBF_TOKEN_PRNSTRING_get();
  public final static char CBF_TOKEN_TDQSTRING = cbfJNI.CBF_TOKEN_TDQSTRING_get();
  public final static char CBF_TOKEN_TSQSTRING = cbfJNI.CBF_TOKEN_TSQSTRING_get();
  public final static char CBF_TOKEN_BKTITEM = cbfJNI.CBF_TOKEN_BKTITEM_get();
  public final static int CBF_CASE_INSENSITIVE = cbfJNI.CBF_CASE_INSENSITIVE_get();
  public final static int CBF_CASE_SENSITIVE = cbfJNI.CBF_CASE_SENSITIVE_get();
  public final static int CBF_INTEGER = cbfJNI.CBF_INTEGER_get();
  public final static int CBF_FLOAT = cbfJNI.CBF_FLOAT_get();
  public final static int CBF_CANONICAL = cbfJNI.CBF_CANONICAL_get();
  public final static int CBF_PACKED = cbfJNI.CBF_PACKED_get();
  public final static int CBF_PACKED_V2 = cbfJNI.CBF_PACKED_V2_get();
  public final static int CBF_BYTE_OFFSET = cbfJNI.CBF_BYTE_OFFSET_get();
  public final static int CBF_PREDICTOR = cbfJNI.CBF_PREDICTOR_get();
  public final static int CBF_NONE = cbfJNI.CBF_NONE_get();
  public final static int CBF_COMPRESSION_MASK = cbfJNI.CBF_COMPRESSION_MASK_get();
  public final static int CBF_FLAG_MASK = cbfJNI.CBF_FLAG_MASK_get();
  public final static int CBF_UNCORRELATED_SECTIONS = cbfJNI.CBF_UNCORRELATED_SECTIONS_get();
  public final static int CBF_FLAT_IMAGE = cbfJNI.CBF_FLAT_IMAGE_get();
  public final static int CBF_NO_EXPAND = cbfJNI.CBF_NO_EXPAND_get();
  public final static int CBF_LOGERROR = cbfJNI.CBF_LOGERROR_get();
  public final static int CBF_LOGWARNING = cbfJNI.CBF_LOGWARNING_get();
  public final static int CBF_LOGWOLINE = cbfJNI.CBF_LOGWOLINE_get();
  public final static int CBF_LOGWOCOLUMN = cbfJNI.CBF_LOGWOCOLUMN_get();
  public final static int CBF_LOGSTARTLOC = cbfJNI.CBF_LOGSTARTLOC_get();
  public final static int CBF_LOGCURRENTLOC = cbfJNI.CBF_LOGCURRENTLOC_get();
  public final static int PLAIN_HEADERS = cbfJNI.PLAIN_HEADERS_get();
  public final static int MIME_HEADERS = cbfJNI.MIME_HEADERS_get();
  public final static int MSG_NODIGEST = cbfJNI.MSG_NODIGEST_get();
  public final static int MSG_DIGEST = cbfJNI.MSG_DIGEST_get();
  public final static int MSG_DIGESTNOW = cbfJNI.MSG_DIGESTNOW_get();
  public final static int MSG_DIGESTWARN = cbfJNI.MSG_DIGESTWARN_get();
  public final static int PAD_1K = cbfJNI.PAD_1K_get();
  public final static int PAD_2K = cbfJNI.PAD_2K_get();
  public final static int PAD_4K = cbfJNI.PAD_4K_get();
  public final static int PARSE_NOBRACKETS = cbfJNI.PARSE_NOBRACKETS_get();
  public final static int PARSE_BRACKETS = cbfJNI.PARSE_BRACKETS_get();
  public final static int PARSE_LIBERAL_BRACKETS = cbfJNI.PARSE_LIBERAL_BRACKETS_get();
  public final static int PARSE_TRIPLE_QUOTES = cbfJNI.PARSE_TRIPLE_QUOTES_get();
  public final static int PARSE_NOTRIPLE_QUOTES = cbfJNI.PARSE_NOTRIPLE_QUOTES_get();
  public final static int PARSE_WIDE = cbfJNI.PARSE_WIDE_get();
  public final static int HDR_DEFAULT = cbfJNI.HDR_DEFAULT_get();
  public final static int MIME_NOHEADERS = cbfJNI.MIME_NOHEADERS_get();
  public final static int CBF = cbfJNI.CBF_get();
  public final static int CIF = cbfJNI.CIF_get();
  public final static int ENC_NONE = cbfJNI.ENC_NONE_get();
  public final static int ENC_BASE64 = cbfJNI.ENC_BASE64_get();
  public final static int ENC_BASE32K = cbfJNI.ENC_BASE32K_get();
  public final static int ENC_QP = cbfJNI.ENC_QP_get();
  public final static int ENC_BASE10 = cbfJNI.ENC_BASE10_get();
  public final static int ENC_BASE16 = cbfJNI.ENC_BASE16_get();
  public final static int ENC_BASE8 = cbfJNI.ENC_BASE8_get();
  public final static int ENC_FORWARD = cbfJNI.ENC_FORWARD_get();
  public final static int ENC_BACKWARD = cbfJNI.ENC_BACKWARD_get();
  public final static int ENC_CRTERM = cbfJNI.ENC_CRTERM_get();
  public final static int ENC_LFTERM = cbfJNI.ENC_LFTERM_get();
  public final static int ENC_DEFAULT = cbfJNI.ENC_DEFAULT_get();
}
