/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iucr.cbflib;

public class doubleP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public doubleP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(doubleP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbfJNI.delete_doubleP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public doubleP() {
    this(cbfJNI.new_doubleP(), true);
  }

  public void assign(double value) {
    cbfJNI.doubleP_assign(swigCPtr, this, value);
  }

  public double value() {
    return cbfJNI.doubleP_value(swigCPtr, this);
  }

  public SWIGTYPE_p_double cast() {
    long cPtr = cbfJNI.doubleP_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static doubleP frompointer(SWIGTYPE_p_double t) {
    long cPtr = cbfJNI.doubleP_frompointer(SWIGTYPE_p_double.getCPtr(t));
    return (cPtr == 0) ? null : new doubleP(cPtr, false);
  }

}
