/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iucr.cbflib;

public class SWIGTYPE_p_cbf_file {
  private long swigCPtr;

  protected SWIGTYPE_p_cbf_file(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_cbf_file() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_cbf_file obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

