output32/JCBridge.o : JCBridge.cpp JCBridge.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/String.h JNIException.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/CallTrace.h \
 ../../../embl-cca.git/org.embl.cca.utils/cpp/String.h \
 /opt/sun-jdk-1.6.0.45/include/jni.h \
 /opt/sun-jdk-1.6.0.45/include/linux/jni_md.h
